name: Manual
version: 2.1.0
description: A perfect layout for manuals. With multi-language-support and a thumb register.
author: Sebastian Schürmanns
license: MIT
website: https://trendschau.net
sizes: A5
graphic: Camera by Martin Chapman, Noun Project

customforms:
  fields:
    fieldsettitlepage:
      type: fieldset
      legend: Covertext and Fly Title
      fields:
        title:
          type: text
          label: Title of your eBook
        subtitle:
          type: text
          label: Subtitle of your eBook
        author:
          type: text
          label: Author
        edition:
          type: text
          label: Edition
        flytitle:
          type: checkbox
          label: Fly title
          checkboxlabel: Add a fly title after the cover. 
    fieldsetcoverdesign:
      type: fieldset
      legend: Cover Design
      fields:
        logo:
          type: image
          label: Upload your LOGO
          description: only jpg or png accepted. Will be added to the cover bottom area
        coverimage:
          type: image
          label: Upload a cover image
          description: only jpg or png accepted. The image will be integrated on the cover below the text.
        primarycolor:
          type: text 
          label: Primary Background Color
          description: The background color of the top area. Will also be used for the active thumb register, links, text-backgrounds and more.
          css: w-half
        primaryfontcolor:
          type: text
          label: Primary Font Color
          description: The font color of the top area. Will also be used for the active thumb register.
          css: w-half
        secondarycolor:
          type: text
          label: Secondary Background Color
          description: The background color of the bottom area. Will also be used of the inactive thumb register.
          css: w-half
        secondaryfontcolor:
          type: text
          label: Secondary Font Color
          description: The font color of the bottom area. Will also be used for the inactive thumb register.
          css: w-half
    fieldsetfonts:
      type: fieldset
      legend: Text
      fields:
        fontheadline:
          type: select
          label: font for headlines
          css: w-half
          options:
            'Noto Serif': Noto Serif
            'Open Sans': Open Sans
            'Jost': Jost
        fontbody:
          type: select
          label: font for body text
          css: w-half
          options:
            'Noto Serif': Noto Serif
            'Open Sans': Open Sans
            'Jost': Jost
        fontsize:
          type: number
          label: General font size for body text
          css: w-half
        textalign:
          type: select
          label: text alignment 
          css: w-half
          options:
            justify: justify
            left: left
        hyphens:
          type: select
          label: hyphens 
          css: w-half
          options:
            auto: auto
            none: none
    fieldsetimprint:
      type: fieldset
      legend: Imprint
      fields:
        imprint:
          type: textarea
          label: Text for imprint (use markdown)
          description: Keep empty to skip the imprint.
    fieldsettoc:
      type: fieldset
      legend: Table of Contents
      fields:
        toc:
          type: checkbox
          label: Table of contents
          checkboxlabel: Add an automatically generated table of contents.
        toctitle:
          type: text
          label: Title for the table of contents page
        toclevel:
          type: number
          label: How many headline-levels (1-6) should be included?
        toccounter:
          type: checkbox
          label: ToC Counter
          checkboxlabel: Add a counter before the headlines.
    fieldsetblurb:
      type: fieldset
      legend: Blurb
      fields:
        blurb:
          type: textarea
          label: Text for the blurb (use markdown)
          description: Text will be displayed at the bottom with small font. Keep empty to skip the blurb.
    fieldsetemptypages:
      type: fieldset
      legend: Empty Pages
      fields:
        hideemptypages:
          type: checkbox
          checkboxlabel: Do not add empty pages before content elements like imprint, table of content and book-chapters.
    fieldsetimagequality:
      type: fieldset
      legend: Image Quality
      fields:
        originalimages:
          type: checkbox
          checkboxlabel: Use original images and do not resize them (use this for print only).
