name: Report
version: 2.0.0
description: A modern layout for reports and similar publications in A4-format. Change font-sizes, font-families, brand-colors, and much more.
author: Sebastian Schürmanns, trendschau.net
licence: CC BY 3.0
link: https://trendschau.net
sizes: A4

customforms:
  fields:
    fieldsettitlepage:
      type: fieldset
      legend: Cover
      fields:
        title:
          type: text
          label: Title of your eBook
        subtitle:
          type: text
          label: Subtitle of your eBook
        coverlefttext:
          type: textarea
          label: Text in left botton corner (use markdown)
        coverrighttext:
          type: textarea
          label: Text in right botton corner (use markdown)
        logo:
          type: image
          label: Upload your LOGO
          description: only jpg or png accepted. Will be added to the cover bottom area
        logoleft:
          type: checkbox
          label: Position of logo
          checkboxlabel: Left instead of right 
        coverimage:
          type: image
          label: Upload a cover image
          description: only jpg or png accepted. The image will be integrated on the cover below the text.
        coverimagefit:
          type: checkbox
          label: Full size cover image
          checkboxlabel: Adjust the cover image to fill the whole area.
        coverimagewidth:
          type: text
          label: Maximum width of cover image in px or %
          placeholder: 400px
          description: Please uncheck the full-size option if you use a maximum width
        primarycolor:
          type: text 
          label: Background color for cover
          placeholder: cadetblue
          class: medium
        primaryfontcolor:
          type: text
          label: Font color for cover
          placeholder: white
          class: medium
        secondarycolor:
          type: text
          label: Background color of cover-bottom
          placeholder: cadetblue
          class: medium
        secondaryfontcolor:
          type: text
          label: Font color of cover-bottom
          placeholder: white
          class: medium
    fieldsetfonts:
      type: fieldset
      legend: Text
      fields:
        fontheadline:
          type: select
          label: font for headlines
          class: medium
          options:
            'Noto Serif': Noto Serif
            'Open Sans': Open Sans
            'Jost': Jost
        fontheadlinecolor:
          type: text
          label: Font color for headlines
          placeholder: cadetblue
          class: medium
        fontbody:
          type: select
          label: font for body text
          class: medium
          options:
            'Noto Serif': Noto Serif
            'Open Sans': Open Sans
            'Jost': Jost
        fontbodycolor:
          type: text
          label: Font color for body text
          placeholder: '#333'
          class: medium
        linkcolor:
          type: text
          label: Font color for links
          placeholder: cadetblue
          class: medium
        contrastcolor:
          type: text
          label: contrast color, e.g. for table headers with white text
          placeholder: cadetblue
          class: medium
        fontsize:
          type: number
          label: General font size for body text
        textalign:
          type: select
          label: text alignment 
          options:
            justify: justify
            left: left
        hyphens:
          type: select
          label: hyphens 
          options:
            auto: auto
            none: none
    fieldsetimprint:
      type: fieldset
      legend: Imprint
      fields:
        imprint:
          type: textarea
          label: Text for imprint (use markdown)
          description: Keep empty to skip the imprint.
    fieldsettoc:
      type: fieldset
      legend: Table of Contents
      fields:
        toc:
          type: checkbox
          label: Table of contents
          checkboxlabel: Add an automatically generated table of contents.
        toctitle:
          type: text
          label: Title for the table of contents page
        toclevel:
          type: number
          label: How many headline-levels (1-6) should be included?
        toccounter:
          type: checkbox
          label: ToC Counter
          checkboxlabel: Add a counter before the headlines in text and Table of Contents.
        tocindent:
          type: checkbox
          label: ToC Indent
          checkboxlabel: Indent elements in the table of contents hierarchically.
    fieldsetrunningfooter:
      type: fieldset
      legend: Paging and Running Footer
      fields:
        totalpages:
          type: checkbox
          label: Total Pages
          checkboxlabel: Show total pages in paging like "34 / 60"
        footertitle:
          type: checkbox
          label: Title in Footer
          checkboxlabel: Show current title (h1) in footer
    fieldsetblurb:
      type: fieldset
      legend: Blurb
      fields:
        blurb:
          type: textarea
          label: Text for the blurb (use markdown)
          description: Text will be displayed at the bottom with small font. Keep empty to skip the blurb.
    fieldsetemptypages:
      type: fieldset
      legend: Empty Pages
      fields:
        hideemptypages:
          type: checkbox
          checkboxlabel: Do not add empty pages before content elements like imprint, table of content and book-chapters.
    fieldsetimagequality:
      type: fieldset
      legend: Image Quality
      fields:
        originalimages:
          type: checkbox
          checkboxlabel: Use original images and do not resize them (use this for print only).
