Name: Report
Copyright: Sebastian Schürmanns, trendschau.net
Licence: Creative Commons BY 3.0
Link: https://trendschau.net
Sizes: A4 (210mm x 297mm)

customforms:
  fields:
    fieldsettitlepage:
      type: fieldset
      legend: Cover
      fields:
        title:
          type: text
          label: Title of your eBook
        subtitle:
          type: text
          label: Subtitle of your eBook
        coverlefttext:
          type: textarea
          label: Text in left botton corner (use markdown)
        coverrighttext:
          type: textarea
          label: Text in right botton corner (use markdown)
        coverimage:
          type: image
          label: Upload a cover image
          description: only jpg or png accepted. The image will be integrated on the cover below the text.
        logo:
          type: image
          label: Upload your LOGO
          description: only jpg or png accepted. Will be added to the cover bottom area
        primarycolor:
          type: text 
          label: Color for cover background and headlines
          description: The background color of the top area. Will also be used for the active thumb register, links, text-backgrounds and more.
        primaryfontcolor:
          type: text
          label: Font color for headlines on cover
          description: The font color of the top area. Will also be used for the active thumb register.
        secondarycolor:
          type: text
          label: Background color of bottom area of the cover
          description: The background color of the bottom area. Will also be used of the inactive thumb register.
        secondaryfontcolor:
          type: text
          label: Font color of bottom area of the cover
          description: The font color of the bottom area. Will also be used for the inactive thumb register.
    fieldsetfonts:
      type: fieldset
      legend: Text
      fields:
        fontsize:
          type: number
          label: General font size for body text
        fontbody:
          type: select
          label: font for body text
          options:
            'Noto Serif': Noto Serif
            'Open Sans': Open Sans
            'Jost': Jost
        fontheadline:
          type: select
          label: font for headlines
          options:
            'Noto Serif': Noto Serif
            'Open Sans': Open Sans
            'Jost': Jost
        textalign:
          type: select
          label: text alignment 
          options:
            justify: justify
            left: left
        hyphens:
          type: select
          label: hyphens 
          options:
            auto: auto
            none: none
    fieldsetimprint:
      type: fieldset
      legend: Imprint
      fields:
        imprint:
          type: textarea
          label: Text for imprint (use markdown)
          description: Keep empty to skip the imprint.
    fieldsettoc:
      type: fieldset
      legend: Table of Contents
      fields:
        toc:
          type: checkbox
          label: Table of contents
          checkboxlabel: Add an automatically generated table of contents.
        toctitle:
          type: text
          label: Title for the table of contents page
        toclevel:
          type: number
          label: How many headline-levels (1-6) should be included?
        toccounter:
          type: checkbox
          label: ToC Counter
          checkboxlabel: Add a counter before the headlines in text and Table of Contents.
        tocindent:
          type: checkbox
          label: ToC Indent
          checkboxlabel: Indent elements in the table of contents hierarchically.
    fieldsetrunningfooter:
      type: fieldset
      legend: Paging and Running Footer
      fields:
        totalpages:
          type: checkbox
          label: Total Pages
          checkboxlabel: Show total pages in paging like "34 / 60"
        footertitle:
          type: checkbox
          label: Title in Footer
          checkboxlabel: Show current title (h1) in footer
    fieldsetblurb:
      type: fieldset
      legend: Blurb
      fields:
        blurb:
          type: textarea
          label: Text for the blurb (use markdown)
          description: Text will be displayed at the bottom with small font. Keep empty to skip the blurb.
    fieldsetimagequality:
      type: fieldset
      legend: Image Quality
      fields:
        originalimages:
          type: checkbox
          checkboxlabel: Use original images and do not resize them (use this for print only).
